# Generated by Django 4.0.4 on 2022-08-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_inquiry_listing_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='listing_details',
        ),
    ]
