# Generated by Django 4.1.4 on 2023-01-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="ar-realty/users/avatar/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_avatar",
            field=models.CharField(
                default="https://res.cloudinary.com/iamalmiir/image/upload/v1672591048/catAvatar_iakq5p_fm3hei.webp",
                max_length=255,
            ),
        ),
    ]
