# Generated by Django 4.1.4 on 2023-01-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="default_avatar",
        ),
    ]
