# Generated by Django 4.1.1 on 2022-09-29 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 9, 29, 17, 25, 51, 416543)
            ),
        ),
    ]
