# Generated by Django 4.1.1 on 2022-11-28 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 11, 27, 19, 31, 8, 462873)
            ),
        ),
    ]
