# Generated by Django 4.1.4 on 2023-01-08 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 8, 17, 17, 33, 783482)
            ),
        ),
    ]
