# Generated by Django 4.2 on 2023-06-10 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_alter_listing_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ("-publishedAt",)},
        ),
        migrations.AlterUniqueTogether(
            name="listing",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_1",
            field=models.ImageField(blank=True, upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_2",
            field=models.ImageField(blank=True, upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_3",
            field=models.ImageField(blank=True, upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_4",
            field=models.ImageField(blank=True, upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_5",
            field=models.ImageField(blank=True, upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_main",
            field=models.ImageField(upload_to="ar/listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="publishedAt",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name="listing",
            name="pub_date",
        ),
    ]
