# Generated by Django 4.0.4 on 2022-09-01 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 31, 22, 59, 44, 12421)),
        ),
    ]
