# Generated by Django 4.2 on 2023-06-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realtors", "0002_alter_realtor_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="photo",
            field=models.ImageField(blank=True, upload_to="ar/realtors/"),
        ),
    ]
